config/routes.rb
Rails.application.routes.draw do
  root "projects#index"

  namespace :admin do
      resources :roles
      resources :projects
      resources :pages
      resources :users

      root to: "users#index"
    end
  devise_for :users

  resources :projects, path: '' do
      resources :pages do
        # collection do
        #   post :search
        # end
      end
  end


end

app/views/shared/_navbar.html.haml
%nav.top-0.sticky.z-10.bg-white.border-b
  .px-2.sm:px-6.lg:px-8
    .relative.flex.h-16.items-center.justify-between
      .absolute.inset-y-0.left-0.flex.items-center.sm:hidden
        / Mobile menu button
        %button.inline-flex.items-center.justify-center.rounded-md.p-2.text-gray-400.hover:bg-gray-700.hover:text-white.focus:outline-none.focus:ring-2.focus:ring-inset.focus:ring-white{"aria-controls" => "mobile-menu", "aria-expanded" => "false", type: "button"}
          %span.sr-only Open main menu
          /
            Icon when menu is closed.

            Menu open: "hidden", Menu closed: "block"
          %svg.block.h-6.w-6{"aria-hidden" => "true", fill: "none", stroke: "currentColor", "stroke-width" => "1.5", viewbox: "0 0 24 24"}
            %path{d: "M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
          /
            Icon when menu is open.

            Menu open: "block", Menu closed: "hidden"
          %svg.hidden.h-6.w-6{"aria-hidden" => "true", fill: "none", stroke: "currentColor", "stroke-width" => "1.5", viewbox: "0 0 24 24"}
            %path{d: "M6 18L18 6M6 6l12 12", "stroke-linecap" => "round", "stroke-linejoin" => "round"}
      .flex.flex-1.items-center.justify-center.sm:items-stretch.sm:justify-start
        .sm:ml-6.sm:block
          .flex.space-x-1
            / Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white"
            = link_to 'New space', new_project_path, class: "bg-accent text-white rounded-md px-3 py-2 text-sm font-medium hover:bg-accent-light"
      .flex.items-center.pr-2.items-stretch
        -# - if @project
        -#   %button#search_button.flex.items-center.w-48.pl-3.bg-gray-100.rounded-3xl.text-gray-400.text-sm.border-2.border-gray-100.hover:border-accent
        -#     %svg#Capa_1.text-gray-600.h-4.w-4.mr-2.fill-current{height: "512px", style: "enable-background:new 0 0 56.966 56.966;", version: "1.1", viewbox: "0 0 56.966 56.966", width: "512px", x: "0px", "xml:space" => "preserve", xmlns: "http://www.w3.org/2000/svg", "xmlns:xlink" => "http://www.w3.org/1999/xlink", y: "0px"}
        -#       %path{d: "M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z"}
        -#     Search for docs
        .relative.ml-3
          %div
            %button#user-menu-button.rounded-full.bg-gray-800.text-sm.focus:outline-none.focus:ring-2.focus:ring-white.focus:ring-offset-2.focus:ring-offset-gray-800{"aria-expanded" => "false", "aria-haspopup" => "true", type: "button"}
              %span.sr-only Open user menu
              %img.h-8.w-8.rounded-full{alt: "", src: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"}
          .absolute.right-0.z-10.mt-2.w-48.origin-top-right.rounded-md.bg-white.py-1.shadow-lg.ring-1.ring-black.ring-opacity-5.focus:outline-none{"aria-labelledby" => "user-menu-button", "aria-orientation" => "vertical", role: "menu", tabindex: "-1"}
            / Active: "bg-gray-100", Not Active: ""
            %a#user-menu-item-0.block.px-4.py-2.text-sm.text-gray-700{href: "#", role: "menuitem", tabindex: "-1"} My profile
            = link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, id: "user-menu-item-2", class: "block px-4 py-2 text-sm text-gray-700"
  / Mobile menu, show/hide based on menu state.
  #mobile-menu.sm:hidden
    .space-y-1.px-2.pb-3.pt-2
      / Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white"
      %a.bg-gray-900.text-white.block.rounded-md.px-3.py-2.text-base.font-medium{"aria-current" => "page", href: "#"} Dashboard

app/views/shared/_search_form.html.haml
-# - if @project.id.present?
-#   = form_with url: search_project_pages_path(@project), method: :post, data: { controller: "search" } do |form|
-#     .relative.text-gray-600
-#       %i.fa-solid.fa-magnifying-glass.fa-xl.absolute.left-0.top-1.mt-6.ml-3.text-accent
-#       = form.search_field :search,
-#       data: {"search-target": "search_field", action: "input->search#debouncedSearch"},
-#       name: "search",
-#       placeholder: "Search for documentation...",
-#       class: "border-2 border-accent bg-white w-full h-14 px-10 pr-16 mb-2 rounded-lg focus:outline-0"
-#       #suggestions{data: {"search-target": "search_suggestions"}}

app/views/shared/_search_modal.html.haml
#search_modal.relative.z-50.hidden{"aria-labelledby": "modal-title", "aria-modal": "true", role: "dialog"}
  .fixed.inset-0.bg-gray-500.bg-opacity-75.transition-opacity
  .fixed.inset-0.z-10.overflow-y-auto
    #search-modal-backdrop.flex.min-h-full.justify-center.p-4.mt-5.text-center.items-start.sm:p-0
      .relative.transform.overflow-hidden.rounded-lg.bg-white.text-left.shadow-xl.transition-all{class: "w-5/12"}
        .bg-gray-100.sm:p-3
          - if @project
            = render "shared/search_form"

app/views/shared/_search_results.html.haml
- if pages.empty?
  %span.text-center.block.text-lg No results 😶‍🌫️
- else
  %ul
    - pages.each do |page|
      %li.list-none.bg-white.rounded-md.mb-2
        = link_to highlight(page.title, params[:search]), project_page_path(@project, page), class: "w-full h-full block rounded-md p-4 hover:bg-accent hover:text-white"

app/views/shared/_sidebar.html.haml
#docs-sidebar.h-screen.fixed.z-20.w-64.bg-white.overflow-y-auto.border-r.border-gray-200.pt-7.pb-10.scrollbar-y
  %b.text-gray-500.pl-1= @project.title.upcase
  = render "pages/top_level_pages"