config/routes.rb
Rails.application.routes.draw do
  root "projects#index"

  namespace :admin do
      resources :roles
      resources :projects
      resources :pages
      resources :users

      root to: "users#index"
    end
  devise_for :users

  resources :projects, path: '' do
      resources :pages do
        # collection do
        #   post :search
        # end
      end
  end


end

app/models/project.rb
class Project < ApplicationRecord
  before_save :create_slug

  has_many :pages

  validates :title, presence: true, uniqueness: true
  validates :description, length: { minimum: 10 }

  def to_param
    slug
  end

  private

  def create_slug
    self.slug = title&.parameterize
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project

  def index
    @projects = Project.all
    # authorize @projects
  end

  def show
    # authorize @project
    if (@page = @project.pages.top_level.first)
      redirect_to project_page_path(@project, @page)
    else
      @page = @project.pages.create(title: "First page in #{@project.title}")
      # authorize @page
      redirect_to edit_project_page_path(@project, @page)
    end
  end

  def new
    @project = Project.new
    # authorize @project
  end

  def create
    @project = Project.new(project_params)
    # authorize @project
    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
        # create first page automatically
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # TODO: dependent: destroy
    # authorize @project
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find_by(slug: params[:id])
    end

    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_with(model: @project, class: "contents") do |form|
  - if @project.errors.any?
    #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
      %h2
        = pluralize(@project.errors.count, "error")
        prohibited this project from being saved:
      %ul
        - @project.errors.each do |error|
          %li= error.full_message
  .my-5
    = form.label :title
    = form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :description
    = form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/projects/_project.html.haml
%div{:id => "#{dom_id project}"}
  %p.my-5
    %strong.block.font-medium.mb-1 Title:
    = project.title
  %p.my-5
    %strong.block.font-medium.mb-1 Description:
    = project.description
  - if action_name != "show"
    = link_to "Show this project", project, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    = link_to 'Edit this project', edit_project_path(project), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
    %hr.mt-6/

app/views/projects/_sidebar.html.haml
/ Navigation Toggle
%button.text-gray-500.hover:text-gray-600{"aria-controls" => "docs-sidebar", "aria-label" => "Toggle navigation", "data-hs-overlay" => "#docs-sidebar", type: "button"}
  %span.sr-only Toggle Navigation
  %svg.w-5.h-5{fill: "currentColor", height: "16", viewbox: "0 0 16 16", width: "16"}
    %path{d: "M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z", "fill-rule" => "evenodd"}
/ End Navigation Toggle
#docs-sidebar.hs-overlay.hs-overlay-open:translate-x-0.-translate-x-full.transition-all.duration-300.transform.hidden.fixed.top-16.left-0.bottom-0.w-64.bg-white.border-r.border-gray-200.pt-7.pb-10.overflow-y-auto.scrollbar-y.lg:block.lg:translate-x-0.lg:right-auto.lg:bottom-0.dark:scrollbar-y.dark:bg-white.dark:border-grey-light{class: "z-[60]"}
  .px-6
    %a.flex-none.text-xl.font-semibold.dark:text-white{"aria-label" => "Brand", href: "javascript:;"} Brand
  %nav.list-none.p-6.w-full.flex.flex-col.flex-wrap{"data-hs-accordion-always-open" => ""}
    %ul{class: "space-y-1.5"}
    - @project.pages.each do |page|
      %li
        = link_to project_page_path(@project, page), class: "flex items-center py-2 text-sm text-slate-700 rounded-md hover:bg-gray-100.dark:hover:bg-gray-900 dark:text-slate-400 dark:hover:text-slate-300K" do
          = page.title

app/views/projects/edit.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl Editing project
  = render "form", project: @project
  = link_to "Show this project", @project, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to "Back to projects", projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/projects/index.html.haml
.w-full
  - if notice.present?
    %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
  .flex.justify-between.items-center
    %h1.font-bold.text-4xl Projects
  #projects.min-w-full.flex.gap-3.justify-center
    - @projects.each do |project|
      = link_to project_path(project), class: "block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700" do
        %h5.mb-2.text-2xl.font-bold.tracking-tight.text-gray-900.dark:text-white
          = project.title
          %p.font-normal.text-gray-700.dark:text-gray-400
            = project.description

app/views/projects/new.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl New project
  = render "form", project: @project
  = link_to 'Back to projects', projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/projects/show.html.haml
= render "shared/sidebar"
.mx-auto.w-full.flex{:class => "md:w-2/3"}
  .mx-auto
    - if notice.present?
      %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
    = render @project
    = link_to 'Create page', new_project_page_path(@project) , class: "mt-2 rounded-lg py-3 px-5 bg-green text-white inline-block font-medium"
    = link_to 'Edit this project', edit_project_path(@project), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    .inline-block.ml-2
      = button_to 'Destroy this project', project_path(@project), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
    = link_to 'Back to projects', projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"